import 'package:flutter/material.dart';
import '../../data/models/feed_source.dart';
import 'app_colors.dart';

const List<FeedSource> kFeedSources = [
  FeedSource(
    id: 'yc',
    name: 'Y Combinator',
    url: 'https://www.ycombinator.com/blog/rss',
    type: ContentType.article,
    color: AppColors.peach,
    category: 'Startup',
    maxMinutes: 20,
  ),
  FeedSource(
    id: 'a16z',
    name: 'a16z',
    url: 'https://a16z.com/feed/',
    type: ContentType.article,
    color: AppColors.skyBlue,
    category: 'Startup',
    maxMinutes: 20,
  ),
  FeedSource(
    id: 'paul_graham',
    name: 'Paul Graham',
    url: 'http://www.paulgraham.com/rss.html',
    type: ContentType.article,
    color: Color(0xFFFFD166),
    category: 'Startup',
    maxMinutes: 20,
  ),
  FeedSource(
    id: 'pragmatic_engineer',
    name: 'Pragmatic Engineer',
    url: 'https://newsletter.pragmaticengineer.com/feed',
    type: ContentType.article,
    color: AppColors.mint,
    category: 'Kodlama',
    maxMinutes: 20,
  ),
  FeedSource(
    id: 'fireship',
    name: 'Fireship',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA',
    type: ContentType.video,
    color: Color(0xFFFF4757),
    category: 'Kodlama',
    maxMinutes: 12,
    isAtom: true,
  ),
  FeedSource(
    id: 'lenny',
    name: "Lenny's Newsletter",
    url: 'https://www.lennysnewsletter.com/feed',
    type: ContentType.article,
    color: AppColors.pink,
    category: 'Pazarlama',
    maxMinutes: 20,
  ),
  FeedSource(
    id: 'acquired',
    name: 'Acquired',
    url: 'https://feeds.simplecast.com/4T39_jAn',
    type: ContentType.podcast,
    color: AppColors.lavender,
    category: 'Vizyon',
    maxMinutes: 45,
  ),
  FeedSource(
    id: 'lex_fridman',
    name: 'Lex Fridman',
    url: 'https://lexfridman.com/feed/podcast/',
    type: ContentType.podcast,
    color: AppColors.skyBlue,
    category: 'Vizyon',
    maxMinutes: 45,
  ),

  // Türkçe kaynaklar
  FeedSource(
    id: 'webrazzi',
    name: 'Webrazzi',
    url: 'https://webrazzi.com/feed/',
    type: ContentType.article,
    color: Color(0xFF4ECDC4),
    category: 'Startup 🇹🇷',
    maxMinutes: 10,
  ),
  FeedSource(
    id: 'startup_borsa',
    name: 'Startup Borsa',
    url: 'https://startupborsa.com/feed/',
    type: ContentType.article,
    color: Color(0xFFFFB347),
    category: 'Startup 🇹🇷',
    maxMinutes: 10,
  ),
  FeedSource(
    id: 'kodluyoruz',
    name: 'Kodluyoruz',
    url: 'https://medium.com/feed/kodluyoruz',
    type: ContentType.article,
    color: Color(0xFF95E1D3),
    category: 'Kodlama 🇹🇷',
    maxMinutes: 10,
  ),
];
